---
- name: Clear install directory
  become: true
  file:
     path: "{{ inspircd_install_dir }}"
     state: absent

- name: Create install directory
  become: true
  file:
     path: "{{ inspircd_install_dir }}"
     state: directory
     owner: "{{ ansible_user_id }}"
     group: "{{ ansible_user_id }}"

- name: Download inspircd
  git:
    repo: https://github.com/inspircd/inspircd.git
    version: "{{ inspircd_branch }}"
    dest: "{{ inspircd_install_dir }}"

- name: Configure inspircd
  command: ./configure --disable-interactive chdir="{{ inspircd_install_dir }}"

- name: Build inspircd
  command: make chdir="{{ inspircd_install_dir }}"

- name: Install inspircd
  command: make install chdir="{{ inspircd_install_dir }}"
